### ISSUE TITLE
TypeError: Cannot set property 'pause' of undefined

### ISSUE THREAD

**Issue by jeancarlos1111** [Johnhhorton/node-nmap#26]
/home/jean/app_node/hostname_nmap/node_modules/queued-up/index.js:23
        this.action.prototype.pause = this.pause;
                                    ^

TypeError: Cannot set property 'pause' of undefined
    at new Queue (/home/jean/app_node/hostname_nmap/node_modules/queued-up/index.js:23:37)
    at QueuedScan (/home/jean/app_node/hostname_nmap/node_modules/node-nmap/index.js:260:19)
    at QueuedOsAndPortScan (/home/jean/app_node/hostname_nmap/node_modules/node-nmap/index.js:433:5)
    at Object.<anonymous> (/home/jean/app_node/hostname_nmap/index.js:14:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
![captura de pantalla de 2017-06-21 20-48-15](https://user-images.githubusercontent.com/10359567/27412675-2ee9f426-56c4-11e7-9aa7-1eabcdf86161.png)

**Comment by Johnhhorton** [comment]
@jeancarlos1111 I'll look into this. Thanks for the bug report.

**Comment by mainstreetmark** [comment]
I got this one too.

**Comment by dunklesToast** [comment]
Same error here - nmap 7.40 / macOS Sierra

**Comment by openWebX** [comment]
Same here nmap 7.60 / gentoo Linux... Wild guess: Could it be, that the call fails, because newer nmaps require root-priviledges for os-names and mac-addresses?

**Comment by job-so** [comment]
it's related to : Johnhhorton/queued-up#5

**Comment by job-so** [comment]
```diff
-    this._queue = new Queue((host) => {
+    this._queue = new Queue(function (host) {
```

https://github.com/job-so/node-nmap/commit/722590cd8e5c9c7278e5c6510595fa8928acf848#diff-168726dbe96b3ce427e7fedce31bb0bc

**Comment by raphaelsoul** [comment]
@job-so I try to run a queued scan with your revise and got error as follow:
```
/Users/raphaelsoul/hacker/node_modules/node-nmap/index.js:304
        this._queue.done();
                    ^

TypeError: this._queue.done is not a function
    at OsAndPortScan.currentScan.on (/Users/raphaelsoul/hacker/node_modules/node-nmap/index.js:304:21)
    at emitOne (events.js:115:13)
    at OsAndPortScan.emit (events.js:210:7)
    at ChildProcess.child.on (/Users/raphaelsoul/hacker/node_modules/node-nmap/index.js:194:14)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by job-so** [comment]
Hi @raphaelsoul 

Did you use this patch : https://github.com/job-so/node-nmap/commit/722590cd8e5c9c7278e5c6510595fa8928acf848#diff-168726dbe96b3ce427e7fedce31bb0bc
or
this one : [https://github.com/Johnhhorton/queued-up/pull/6](https://github.com/Johnhhorton/queued-up/pull/6)

or a combination of both ?

Is there any fork of your code I may look at ?

Thanks.

Olivier.

**Comment by PierrickI3** [comment]
I am also getting the `TypeError: this._queue.done is not a function` when applying your change to https://github.com/job-so/node-nmap/commit/722590cd8e5c9c7278e5c6510595fa8928acf848#diff-168726dbe96b3ce427e7fedce31bb0bc

Any tips on what else you might need to change?

**Comment by job-so** [comment]
Hi @PierrickI3 , which version of node.js are you using ? 
This patch is working well on v8.7.0

**Comment by PierrickI3** [comment]
Hey @job-so, v8.9.1

**Comment by job-so** [comment]
OK my fault ... :-(
Please try this : 
   - Revert to original **node-nmap** module  : `this._queue = new Queue((host) => {`
   - and patch the **queued-up** module like in this PR : Johnhhorton/queued-up/pull/6 based on this [job-so/queued-up](https://github.com/job-so/queued-up/commit/a353065b957256ebe9d646805cbf54e0321625b4#diff-ed009b6b86b017532ef0489c77de5100)

Let me know if it helps
Olivier.

**Comment by PierrickI3** [comment]
That worked. Thanks @job-so !

**Comment by Johnhhorton** [comment]
#36
